name: gestion_admin_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  # L'SDK Dart 3.8.1 est une version future ou non standard. 
  # J'ai utilisé 3.0.0 comme référence, mais vous pouvez le changer 
  # pour la version stable la plus récente si 3.8.1 n'existe pas.
  sdk: '>=3.0.0 <4.0.0' 

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  
  # DEPENDANCE AJOUTEE CORRECTEMENT POUR LE SÉLECTEUR DE FICHIERS
  file_picker: ^5.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints version ajustée pour la compatibilité avec un SDK récent
  flutter_lints: ^3.0.0 # J'ai mis 3.0.0 qui est une version stable pour 3.x

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # The "assets" key must have a 2-space indentation and be aligned with "uses-material-design".
  assets:
    - assets/images/